### ISSUE TITLE
High usage of CPU when emacs is idle

### ISSUE THREAD

**Issue by xbelanch** [ChillarAnand/real-auto-save#43] opened 2020-04-20 12:16 UTC
See the reddit thread: https://www.reddit.com/r/emacs/comments/g4ojo9/emacs_freezes_on_windows_10/

**Comment by ChillarAnand** [comment] 2020-04-20 12:51
@xbelanch  Thanks for reporting the issue. 

I am not sure why it is adding load on CPU. Will check on a windows machine.

**Comment by xbelanch** [comment] 2020-04-20 16:16
@ChillarAnand check out the last init.el I have before I need to comment the real-auto-save package reference if it helps: https://github.com/xbelanch/personal-emacs-dot-files/tree/development

**Comment by guseggert** [comment] 2020-04-28 16:48
I'm also experiencing this on a Mac.  I think it's related to this commit:  https://github.com/ChillarAnand/real-auto-save/commit/ffef94917e6c7344e7a28472e44a2d8c8588ebd3

When I `(setq real-auto-save-use-idle-timer nil)` the issue goes away.

Profiler output:

```
- timer-event-handler                                            7054  81%
 - apply                                                         6654  77%
  - real-auto-save-buffers                                       3164  36%
   - real-auto-save-restart-timer                                2416  27%
    - real-auto-save-start-timer                                 1827  21%
     - run-with-idle-timer                                       1698  19%
      - timer-activate-when-idle                                  792   9%
       - timer--activate                                          607   7%
          timer--time-less-p                                      459   5%
          timerp                                                   13   0%
      - timer-set-idle-time                                       423   4%
         seconds-to-time                                          129   1%
       - timer--time-setter                                        47   0%
          timerp                                                   21   0%
      - timer-set-function                                         59   0%
         timerp                                                    24   0%
    - cancel-timer                                                167   1%
       timerp                                                      39   0%
```

**Comment by conao3** [comment] 2020-04-28 18:05
After #42 change, all my CPU is fully occupied by Emacs.
Are you have any suggestions?
Is it working well in your environment?

Run Emacs using below debug init.el and open `~/.debug.emacs.d/real-auto-save/init.el`, Emacs use 100% of one CPU.

## init.el
```emacs-lisp
;; ~/.debug.emacs.d/real-auto-save/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/{{pkg}}/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(prog1 "prepare leaf"
  (prog1 "package"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize))

  (prog1 "leaf"
    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf))))

(leaf real-auto-save
  :ensure t
  :hook (find-file-hook)
  :config
  (real-auto-save-activate-advice))
```

## Screenshots
![Screenshot_2020-04-29_02-26-48](https://user-images.githubusercontent.com/4703128/80519183-8cf8d580-89c2-11ea-968b-49990abece39.png)
![Screenshot_2020-04-29_02-26-31](https://user-images.githubusercontent.com/4703128/80519192-8f5b2f80-89c2-11ea-8fb3-923a952e6e73.png)

## Environment:
```shell
$ uname -a
Linux conao-manjaro-helios 5.4.35-1-MANJARO #1 SMP PREEMPT Thu Apr 23 10:54:43 UTC 2020 x86_64 GNU/Linux
conao-manjaro-helios:~/dev/repos/leaf-keywords.el conao


$ emacs --version
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by novoid** [comment] 2020-04-28 20:50
I can confirm this issue with:
- elpa/real-auto-save-20200418.405
- emacs-version 26.3 on (X)Ubuntu 20.04 LTS
- emacs-version 26.1 on Debian stable 10 Buster

My configuration:
```
(use-package real-auto-save
  :ensure t
  :after org
  :config
  (add-hook 'org-mode-hook 'real-auto-save-mode)
  (setq real-auto-save-use-idle-timer t)
  (setq real-auto-save-interval 60)
  (real-auto-save-activate-advice)
)
```

After `real-auto-save-interval` of emacs idle time (not system idle time), one CPU core starts working on the emacs process. Switching back to emacs does kill this CPU usage pattern. Again, after `real-auto-save-interval` of emacs idle time, one CPU core starts working again.

When I use `(setq real-auto-save-use-idle-timer nil)` this does not happen. When I don't open an Org mode file, this does not happen (most likely because `:after org` and `(add-hook 'org-mode-hook 'real-auto-save-mode)`).

**Comment by ChillarAnand** [comment] 2020-04-29 04:57
Thanks, @conao3 for the fix. 

This issue is fixed in the latest version.

**Comment by novoid** [comment] 2020-04-29 07:41
I can confirm that this fix resolves the issue at my side.

**Comment by ChillarAnand** [comment] 2020-04-29 10:23
Thanks, @novoid 

Closing this issue. If anyone is still facing this issue with latest version, please re-open it.

**Closed as completed by ChillarAnand** 2020-04-29 10:23 UTC
